### ISSUE TITLE
Shadowing of bitcart.coin

### ISSUE THREAD

**Issue by GodSaveTheDoge** [bitcartcc/bitcart-sdk#47]
The variable used in the for loop in [bitcart/\_\_init\_\_.py](https://github.com/bitcartcc/bitcart-sdk/blob/14981326e5476781fe83a1ebf6edd016156264d0/bitcart/__init__.py#L9) shadows `bitcart/coin.py`.

```python
>>> import bitcart.coin
>>> bitcart.coin # this isn't the module, this is the last coin in COINS.values()
<class 'bitcart.coins.grs.GRS'>
>>>
```

**Comment by MrNaif2018** [comment]
That's not supposed to be used directly anyway, no?

**Comment by GodSaveTheDoge** [comment]
I guess not, it was just an heads up since I don't think it's intentional

**Comment by MrNaif2018** [comment]
Whether it is or is not, what the package exports is defined by __all__. In general other kind of access is not always possible
You can always do
from bitcart.coin import Coin
if needed
Closing this, feel free to re-open
